/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include<stdio.h>
#include <stdint.h>


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define RCC_BASE_ADDR 0x40023800UL
#define RCC_CFGR_OFFSET (0x08UL)
#define RCC_CFGR_ADDR (RCC_BASE_ADDR+RCC_CFGR_OFFSET)


#define RCC_AHB1ENR_BASE    (0x30UL)
#define RCC_AHB1ENR_ADDR (RCC_BASE_ADDR+RCC_AHB1ENR_BASE )

#define GPIOA_BASE_ADDR (0x40020000)
#define RCC_GPIO_MODER_BASE (0x00)
#define RCC_GPIO_OTYPER_BASE (0x04)
#define RCC_GPIO_OSPEEDR_BASE (0x08)
#define RCC_GPIO_AFRH_BASE (0x24)

//#define RCC_AHB1ENR_ADDR ( RCC_BASE_ADDR + RCC_AHB1ENR_BASE UL )
#define GPIO_MODER_ADDR GPIOA_BASE_ADDR+RCC_GPIO_MODER_BASE
#define GPIO_AFRH_ADDR (GPIOA_BASE_ADDR+RCC_GPIO_AFRH_BASE  )


int main(void)
{
	//*((volatile uint32_t*)GPIO_MODER_ADDR) &= (0x0);

	uint32_t* pCFGR =(uint32_t* )RCC_CFGR_ADDR;
	*pCFGR &=!(3<<20);
   uint32_t *p_AHB1 = (uint32_t*) RCC_AHB1ENR_ADDR;
   *p_AHB1&=(1<<0);
   uint32_t* p_MODER=(uint32_t*)GPIO_MODER_ADDR;
   *p_MODER &=!(1<<16);
   *p_MODER |=(1<<17);
   uint32_t* p_AFRH =(uint32_t*)GPIO_AFRH_ADDR;
   *p_AFRH &=(0xFFFFFFF0);









}
